### ISSUE TITLE
Itry to inject using ur injector but

### ISSUE THREAD

**Issue by MAX1MDEV** [kalvin-eliazord/CS2_Internal_Trainer#4]
![image](https://github.com/kalvin-eliazord/Corty_Trainer/assets/58599802/1b15bf41-aca9-42e5-be2b-3801cf26487f)
when I press f6, it just pops up ^Z.

**Comment by MAX1MDEV** [comment]
and one more question, how to open the cheat menu?

**Comment by kalvin-eliazord** [comment]
Fixed, please update to the lastest version and try again.

**Comment by MAX1MDEV** [comment]
ok, i try now , and feedback
